docs: add v3 OpenAPI specifications
polyflix/catalog pull request #8
Opened 2023-01-11 08:13 UTC by jlabatut

Update OpenAPI specifications, in order to comply with Polyflix v3 :

- Courses are the only entity now.
- Elements will be stored in `sections`.
- Elements can be `VIDEO`, `QUIZ` and `PAGE`.
- The Catalog service now stores only elements IDs and type (and their order in the course).
- An element should have a `visibility` field (either `PUBLIC`, `PROTECTED` or `PRIVATE`).

2023-01-11 12:50 UTC, jlabatut commented
User stories :

As | I want to be able to
-- | --
a contributor | create a course containing elements (videos, quizzes, pages) inside sections
a contributor | update a course
a contributor | delete a course
a member / a guest | access a course, browse its content (sections/elements)
an admin | manage the course (update/delete it)

2023-01-11 16:47 UTC, kalil-pelissier requested changes

2023-01-11 16:47 UTC, kalil-pelissier commented on src/resources/openapi.yml
> +          description: ""
Remove the description if not needed.

2023-01-11 16:47 UTC, kalil-pelissier commented on src/resources/openapi.yml
> +      responses:
Missing Error response like (401, 403, 5XX)

2023-01-11 16:47 UTC, kalil-pelissier commented on src/resources/openapi.yml
> +          description: ""
Same remove the description if not needed.

2023-01-11 16:47 UTC, kalil-pelissier commented on src/resources/openapi.yml
> +      responses:
Missing Error response like (401, 403, 5XX)

2023-01-11 16:47 UTC, kalil-pelissier commented on src/resources/openapi.yml
> +          description: ""
Remove the description if not needed.

2023-01-11 19:37 UTC, kalil-pelissier approved these changes

2023-01-12 10:45 UTC, LeoFVO approved these changes

2023-01-12 10:45 UTC, merged